### ISSUE TITLE
[UX review] Client adapter configs of SAML needs update

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#538]
When changing the Client adapter config to the Mod Auth Mellon files type, the code should be hidden, as this is a file type that not readable. @edewit 
![image](https://user-images.githubusercontent.com/23331885/115227470-1446d800-a143-11eb-9051-bf12022feeb8.png)

**Comment by jonkoops** [comment]
@yih-wang This should be fixed now, could you verify it's working correctly on your end?

**Comment by yih-wang** [comment]
@jonkoops Thanks for the updates. I found when switching to the "Mod Auth Mellon files" type, the button bar will block the dropdown menu. In that case, users can hardly notice the dropdown is opened when they try to do so.

[Swtich to the "Mod Auth Mellon files" type] 
![image](https://user-images.githubusercontent.com/23331885/128278126-6540f785-57c6-4961-87e6-94731c8b6ebf.png)

[After clicking the dropdown]
![image](https://user-images.githubusercontent.com/23331885/128278147-0ff31215-4c1c-4fae-81a2-f293ed6e7850.png)

I recommend displaying the dropdown above the current modal.
![image](https://user-images.githubusercontent.com/23331885/128278230-99c80fdc-a9b5-490e-acdc-ffc45b2276f3.png)

**Comment by yih-wang** [comment]
Also, I noticed there is a quick rendering to the adaptor file of the current format when I switch between different formats. So when I change the format from "Mod Auth Mellon files" to another type, I can still see the messy code for about 0.2s. Is it possible to avoid that?

![messy code](https://user-images.githubusercontent.com/23331885/128279279-9133485a-0607-4557-bf1c-abf590d10f94.gif)

**Comment by jonkoops** [comment]
The flashing 'Details' section will be fixed by #942. As for the drop-down, this is a bug upstream in Patternfly. I will create an issue for this and attempt to fix it upstream, but I don't think we should block closing this issue on it.

**Comment by jonkoops** [comment]
After talking to the Patternfly team there is a solution available to the dropdown positioning: https://github.com/keycloak/keycloak-admin-ui/pull/943. Look like we can close this issue after it's merged.

**Comment by jonkoops** [comment]
@yih-wang I believe all the issues have been addressed, can you take another look?

**Comment by yih-wang** [comment]
@jonkoops It works well! Thanks!
